import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.requests': 'Requests',
    'nav.offers': 'Offers',
    'nav.messages': 'Messages',
    'nav.profile': 'Profile',
    'nav.admin': 'Admin',
    'nav.vendors': 'Vendors',
    'nav.projects': 'Projects',
    'nav.analytics': 'Analytics',
    'nav.settings': 'Settings',
    'nav.support': 'Support',
    'nav.logout': 'Logout',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.browseRequests': 'Browse Requests',
    'nav.suppliers': 'Suppliers',
    'nav.orders': 'Orders',
    'nav.manageSubscription': 'Manage Subscription',
    'nav.navigation': 'Navigation',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.submit': 'Submit',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.finish': 'Finish',
    'common.start': 'Start',
    'common.stop': 'Stop',
    'common.pause': 'Pause',
    'common.resume': 'Resume',
    'common.reset': 'Reset',
    'common.clear': 'Clear',
    'common.refresh': 'Refresh',
    'common.reload': 'Reload',
    'common.copy': 'Copy',
    'common.paste': 'Paste',
    'common.cut': 'Cut',
    'common.select': 'Select',
    'common.deselect': 'Deselect',
    'common.selectAll': 'Select All',
    'common.deselectAll': 'Deselect All',
    'common.profile': 'Profile',
    'common.signOut': 'Sign Out',
    'common.settings': 'Settings',
    'common.viewAll': 'View All',
    'common.filterByStatus': 'Filter by Status',
    'common.all': 'All',
    'common.pending': 'Pending',
    'common.succeeded': 'Succeeded',
    'common.failed': 'Failed',
    'common.type': 'Type',
    'common.of': 'of',
    'common.urgency': 'Urgency',
    'common.urgent': 'Urgent',
    'common.high': 'High',
    'common.medium': 'Medium',
    'common.low': 'Low',
    
    // Time formatting
    'time.now': 'Now',
    'time.minutesAgo': '{minutes}m ago',
    'time.hoursAgo': '{hours}h ago',
    'time.daysAgo': '{days}d ago',
    'time.minutes': 'minutes',
    'time.hours': 'hours',
    'time.days': 'days',
    
    // Order status
    'orderStatus.pending': 'Pending',
    'orderStatus.confirmed': 'Confirmed',
    'orderStatus.in_progress': 'In Progress',
    'orderStatus.completed': 'Completed',
    'orderStatus.cancelled': 'Cancelled',
    
    // App
    'app.name': 'MWRD',
    'app.tagline': 'Smart B2B Procurement Platform',
    'app.description': 'Connect with vetted service providers for your procurement needs',

    // Landing Footer - NEW TRANSLATIONS
    'landing.footer.taglineText': 'Transform your procurement processes with our intelligent B2B platform. Connect with verified suppliers and streamline your business operations.',
    'landing.footer.company': 'Company',
    'landing.footer.contactUsBtn': 'Contact Us',
    'landing.footer.blog': 'Blog',
    'landing.footer.whyStart': 'Why Start with MWRD',
    'landing.footer.whyMove': 'Why Move to MWRD',
    'landing.footer.pricingSection': 'Pricing',
    'landing.footer.supportSection': 'Support',
    'landing.footer.support': 'Help & Support',
    'landing.footer.helpCenterLink': 'Help Center',
    'landing.footer.documentation': 'Documentation',
    'landing.footer.systemStatus': 'System Status',
    'landing.footer.privacyPolicy': 'Privacy Policy',
    'landing.footer.termsOfService': 'Terms & Conditions',
    'landing.footer.rights': 'All rights reserved.',
    'landing.footer.followUs': 'Follow us',
    
    // Analytics Dashboard
    'analytics.title': 'Analytics Dashboard',
    'analytics.trackActivity': 'Track your activity and performance insights',
    'analytics.last7Days': 'Last 7 days',
    'analytics.last30Days': 'Last 30 days',
    'analytics.last90Days': 'Last 90 days',
    'analytics.totalRequests': 'Total Requests',
    'analytics.activeChats': 'Active Chats',
    'analytics.responseRate': 'Response Rate',
    'analytics.avgResponseTime': 'Avg Response Time',
    'analytics.weeklyActivity': 'Weekly Activity',
    'analytics.weeklyActivityDesc': 'Your requests, messages, and offers over the last 7 days',
    'analytics.requestCategories': 'Request Categories',
    'analytics.requestCategoriesDesc': 'Distribution of your requests by category',
    'analytics.performanceMetrics': 'Performance Metrics',
    'analytics.performanceMetricsDesc': 'Track your progress towards key goals',
    'analytics.quickActions': 'Quick Actions',
    'analytics.quickActionsDesc': 'Common actions to improve your performance',
    'analytics.completeProfile': 'Complete Profile',
    'analytics.addMissingInfo': 'Add missing information',
    'analytics.respondToMessages': 'Respond to Messages',
    'analytics.pendingResponses': 'pending responses',
    'analytics.createNewRequest': 'Create New Request',
    'analytics.findMoreSuppliers': 'Find more suppliers',
    'analytics.profileCompletion': 'Profile Completion',
    'analytics.activeRequests': 'Active Requests',
    'analytics.vendorConnections': 'Vendor Connections',
    'analytics.fromLastWeek': 'from last week',
    'analytics.manufacturing': 'Manufacturing',
    'analytics.technology': 'Technology',
    'analytics.logistics': 'Logistics',
    'analytics.marketing': 'Marketing',
    'analytics.other': 'Other',
    'analytics.monday': 'Mon',
    'analytics.tuesday': 'Tue',
    'analytics.wednesday': 'Wed',
    'analytics.thursday': 'Thu',
    'analytics.friday': 'Fri',
    'analytics.saturday': 'Sat',
    'analytics.sunday': 'Sun',
    'analytics.requests': 'Requests',
    'analytics.messages': 'Messages',
    'analytics.offers': 'Offers',
    'analytics.overview': 'Overview',
    'analytics.completedProjects': 'Completed Projects',
    'analytics.totalRevenue': 'Total Revenue',
    'analytics.requestsOverTime': 'Requests Over Time',
    'analytics.offersByCategory': 'Offers by Category',
    'analytics.topPerformingVendors': 'Top Performing Vendors',
    'analytics.recentActivity': 'Recent Activity',
    'analytics.month': 'Month',
    'analytics.category': 'Category',
    'analytics.vendor': 'Vendor',
    'analytics.revenue': 'Revenue',
    'analytics.projects': 'Projects',
    'analytics.noDataAvailable': 'No data available',
    'analytics.loadingData': 'Loading analytics data...',
    'analytics.refreshData': 'Refresh Data',
    'analytics.exportData': 'Export Data',
    'analytics.dateRange': 'Date Range',
    'analytics.customRange': 'Custom Range',
    
    // Auth
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.logout': 'Logout',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.rememberMe': 'Remember Me',
    'auth.loginSuccess': 'Logged in successfully',
    'auth.loginError': 'Login failed',
    'auth.registerSuccess': 'Account created successfully',
    'auth.registerError': 'Registration failed',
    'auth.logoutSuccess': 'Logged out successfully',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome to MWRD',
    'dashboard.overview': 'Overview',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.statistics': 'Statistics',
    'dashboard.search': 'Search...',
    'dashboard.findOpportunities': 'Find Business Opportunities',
    'dashboard.completedProjects': 'Completed Projects',

    // Vendor Dashboard specific keys
    'vendor.welcome': 'Welcome to your Vendor Dashboard',
    'vendor.subtitle': 'Manage your offers, browse requests, and grow your business',
    'vendor.totalOffers': 'Total Offers',
    'vendor.acceptedOffers': 'Accepted Offers',
    'vendor.pendingOffers': 'Pending Offers',
    'vendor.searchRequests': 'Search available requests...',
    'vendor.filterByCategory': 'Filter by category',
    'vendor.availableRequests': 'Available Requests',
    'vendor.submitOffer': 'Submit Offer',
    'vendor.viewDetails': 'View Details',
    'vendor.submittedThisMonth': 'Submitted this month',
    'vendor.successRate': 'Success rate',
    'vendor.awaitingClientResponse': 'Awaiting client response',
    'vendor.successfullyWon': 'Successfully won',
    'vendor.inProgressCompleted': 'In progress & completed',
    'vendor.winRate': 'Win Rate',
    'vendor.offersWon': 'offers won',
    'vendor.pendingReviews': 'Pending Reviews',
    'vendor.activeProjects': 'Active Projects',
    'vendor.findOpportunities': 'Find Opportunities',
    'vendor.filterDescription': 'Filter and search for RFQs that match your expertise',
    'vendor.opportunitiesFound': 'opportunities found',
    'vendor.availableOpportunities': 'Available Opportunities',
    'vendor.completeVerificationToSubmit': 'Complete verification to submit offers',
    'vendor.submitOffersToWin': 'Submit offers to win projects',
    'vendor.verificationRequired': 'Verification Required',
    'vendor.budget': 'Budget',
    'vendor.negotiable': 'Negotiable',
    'vendor.due': 'Due',
    'vendor.open': 'Open',
    
    // Enhanced vendor dashboard keys
    'vendor.totalOffersDesc': 'Submitted this month',
    'vendor.winRateDesc': 'of {total} offers won',
    'vendor.pendingReviewsDesc': 'Awaiting client response',
    'vendor.activeProjectsDesc': 'In progress & completed',

    // Browse Requests
    'browseRequests.title': 'Browse Requests',
    'browseRequests.subtitle': 'Find and submit offers for procurement requests',
    'browseRequests.searchAndFilter': 'Search & Filter',
    'browseRequests.searchPlaceholder': 'Search requests...',
    'browseRequests.filterByCategory': 'Filter by category',
    'browseRequests.filterDescription': 'Find the perfect opportunities for your business',
    'browseRequests.noResults': 'No requests found',
    'browseRequests.noResultsDesc': 'Try adjusting your search criteria',
    'browseRequests.budget': 'Budget',
    'browseRequests.deadline': 'Deadline',
    'browseRequests.posted': 'Posted',
    'browseRequests.submitOffer': 'Submit Offer',
    'browseRequests.viewDetails': 'View Details',
    
    // Requests
    'requests.title': 'Requests',
    'requests.create': 'Create Request',
    'requests.myRequests': 'My Requests',
    'requests.allRequests': 'All Requests',
    'requests.pending': 'Pending',
    'requests.approved': 'Approved',
    'requests.rejected': 'Rejected',
    'requests.inProgress': 'In Progress',
    'requests.completed': 'Completed',
    
    // My Offers - NEW TRANSLATIONS
    'myOffers.title': 'My Offers',
    'myOffers.subtitle': 'Track and manage your submitted offers',
    'myOffers.noOffers': 'No offers submitted',
    'myOffers.noOffersDesc': 'You haven\'t submitted any offers yet. Browse requests to get started.',
    'myOffers.offerNumber': 'Offer',
    'myOffers.noDescription': 'No description provided',
    'myOffers.price': 'Price',
    'myOffers.priceNotSet': 'Price not set',
    'myOffers.deliveryTime': 'Delivery Time',
    'myOffers.daysDelivery': 'days delivery',
    'myOffers.submitted': 'Submitted',
    'myOffers.clientResponse': 'Client Response',
    'myOffers.status.pending': 'Pending',
    'myOffers.status.approved': 'Approved',
    'myOffers.status.rejected': 'Rejected',
    'myOffers.status.accepted': 'Accepted',

    // Offers
    'offers.title': 'Offers Management',
    'offers.subtitle.vendor': 'Manage your submitted offers to clients',
    'offers.subtitle.client': 'Review and approve submitted offers',
    'offers.create': 'Create Offer',
    'offers.myOffers': 'My Offers',
    'offers.allOffers': 'All Offers',
    'offers.received': 'Received',
    'offers.sent': 'Sent',
    'offers.totalOffers': 'Total Offers',
    'offers.status.approved': 'Approved',
    'offers.status.rejected': 'Rejected',
    'offers.status.pending': 'Pending Review',
    'offers.searchPlaceholder': 'Search offers...',
    'offers.offerStatus': 'Offer Status',
    'offers.allStatus': 'All Status',
    'offers.compare': 'Compare',
    'offers.newOffer': 'New Offer',
    'offers.forRequest': 'For Request:',
    'offers.vendor': 'Vendor:',
    'offers.viewDetails': 'View Details',
    'offers.messageVendor': 'Message Vendor',
    'offers.accept': 'Accept',
    'offers.reject': 'Reject',
    'offers.noOffers': 'No Offers Found',
    'offers.noOffersDesc.search': 'No offers match your search criteria',
    'offers.noOffersDesc.vendor': 'You haven\'t submitted any offers yet. Start by creating a new offer.',
    'offers.noOffersDesc.client': 'No offers have been submitted for your requests yet.',
    'offers.days': 'days',
    'offers.selectOffers': 'Select offers to compare',
    'offers.selectAll': 'Select All',
    'offers.deselectAll': 'Deselect All',
    'offers.compareSelected': 'Compare Selected',
    'offers.offersSelected': 'offers selected',
    'offers.price': 'Price',
    'offers.deliveryTime': 'Delivery Time',
    'offers.submittedOn': 'Submitted on',
    'offers.submittedBy': 'Submitted by',
    'offers.status': 'Status',
    
    // Messages
    'messages.title': 'Messages',
    'messages.newMessage': 'New Message',
    'messages.compose': 'Compose',
    'messages.inbox': 'Inbox',
    'messages.sent': 'Sent',
    'messages.drafts': 'Drafts',
    'messages.trash': 'Trash',
    'messages.communicateWithSuppliers': 'Communicate with suppliers and clients',
    'messages.searchConversations': 'Search conversations...',
    'messages.noMatchingConversations': 'No matching conversations',
    'messages.noConversations': 'No conversations',
    'messages.tryDifferentSearch': 'Try a different search term',
    'messages.startConversation': 'Start a conversation by responding to an offer or request',
    'messages.failedToLoadConversations': 'Failed to load conversations',
    
    // Profile
    'profile.title': 'Profile Settings',
    'profile.subtitle': 'Manage your account information and verification status',
    'profile.edit': 'Edit Profile',
    'profile.settings': 'Profile Settings',
    'profile.personalInfo': 'Personal Information',
    'profile.personalInfoDesc': 'Update your personal details and contact information',
    'profile.companyInfo': 'Company Information',
    'profile.companyInfoDesc': 'Company details and business information',
    'profile.contactInfo': 'Contact Information',
    'profile.fullName': 'Full Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.role': 'Role',
    'profile.address': 'Address',
    'profile.companyName': 'Company Name',
    'profile.bio': 'Company Description & Services',
    'profile.bioClient': 'Company Description',
    'profile.bioPlaceholder': 'Describe your company, services, and expertise...',
    'profile.bioPlaceholderClient': 'Describe your company and business...',
    'profile.portfolioUrl': 'Portfolio URL',
    'profile.saveChanges': 'Save Changes',
    'profile.saving': 'Saving...',
    'profile.serviceCategories': 'Service Categories',
    'profile.serviceCategoriesDesc': 'Select the categories of services you provide. This helps clients find you for relevant requests.',
    'profile.selectedCategories': 'Selected Categories:',
    'profile.saveCategories': 'Save Categories',
    'profile.verification': 'Verification',
    'profile.verificationRequirements': 'Verification Requirements',
    'profile.verificationDesc': 'As a vendor, verification is required to access bidding and order management features',
    'profile.accountSettings': 'Account Settings',
    'profile.accountSettingsDesc': 'Manage your account preferences and security settings',
    'profile.accountStatus': 'Account Status',
    'profile.subscriptionPlan': 'Subscription Plan',
    'profile.memberSince': 'Member Since',
    'profile.verified': 'Verified',
    'profile.rejected': 'Rejected',
    'profile.underReview': 'Under Review',
    'profile.pendingVerification': 'Pending Verification',
    'profile.tabs.profile': 'Profile',
    'profile.tabs.categories': 'Categories',
    'profile.tabs.verification': 'Verification',
    'profile.tabs.settings': 'Settings',
    
    // Theme
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'theme.system': 'System',
    
    // Admin Panel
    'admin.panel': 'Admin Panel',
    'admin.managementDashboard': 'Management Dashboard',
    'admin.adminVersion': 'Admin Version',
    'admin.adminUser': 'Admin User',
    'admin.searchPlaceholder': 'Search admin panel...',
    'admin.notificationsDemo': 'Demo notifications',
    'searching': 'Searching',
    
    // Admin Menu Items
    'admin.menu.dashboard': 'Dashboard',
    'admin.menu.userManagement': 'User Management',
    'admin.menu.allUsers': 'All Users',
    'admin.menu.advancedManagement': 'Advanced Management',
    'admin.menu.userProfiles': 'User Profiles',
    'admin.menu.financial': 'Financial',
    'admin.menu.financialDashboard': 'Financial Dashboard',
    'admin.menu.transactions': 'Transactions',
    'admin.menu.subscriptions': 'Subscriptions',
    'admin.menu.analytics': 'Analytics',
    'admin.menu.platformAnalytics': 'Platform Analytics',
    'admin.menu.userActivity': 'User Activity',
    'admin.menu.reports': 'Reports',
    'admin.menu.contentManagement': 'Content Management',
    'admin.menu.requestsApproval': 'Requests Approval',
    'admin.menu.offersManagement': 'Offers Management',
    'admin.menu.expertConsultations': 'Expert Consultations',
    'admin.menu.system': 'System',
    'admin.menu.settings': 'Settings',
    'admin.menu.themeDesign': 'Theme Design',
    'admin.menu.database': 'Database',
    
    // Orders
    'orders.title': 'Orders',
    'orders.subtitle': 'Track and manage your orders',
    'orders.noOrders': 'No orders found',
    'orders.noOrdersDesc': 'You don\'t have any orders yet. Start by submitting requests or offers.',
    'orders.orderNumber': 'Order',
    'orders.noDescription': 'No description available',
    'orders.amountNotSet': 'Amount not set',
    'orders.created': 'Created',
    'orders.delivery': 'Delivery',
    'orders.viewDetails': 'View Details',
    
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account preferences and settings',
    'settings.tabs.notifications': 'Notifications',
    'settings.tabs.security': 'Security',
    'settings.tabs.language': 'Language',
    'settings.tabs.appearance': 'Appearance',
    'settings.notificationPrefs': 'Notification Preferences',
    'settings.notificationPrefsDesc': 'Choose how you want to receive notifications',
    'settings.emailNotifications': 'Email Notifications',
    'settings.emailNotificationsDesc': 'Receive notifications via email',
    'settings.pushNotifications': 'Push Notifications',
    'settings.pushNotificationsDesc': 'Receive push notifications in your browser',
    'settings.smsNotifications': 'SMS Notifications',
    'settings.smsNotificationsDesc': 'Receive important updates via SMS',
    'settings.marketingComms': 'Marketing Communications',
    'settings.marketingCommsDesc': 'Receive updates about new features and offers',
    'settings.savePreferences': 'Save Preferences',
    'settings.securitySettings': 'Security Settings',
    'settings.securitySettingsDesc': 'Manage your account security and password',
    'settings.currentPassword': 'Current Password',
    'settings.newPassword': 'New Password',
    'settings.confirmPassword': 'Confirm New Password',
    'settings.updatePassword': 'Update Password',
    'settings.languagePrefs': 'Language Preferences',
    'settings.languagePrefsDesc': 'Choose your preferred language for the interface',
    'settings.english': 'English',
    'settings.arabic': 'العربية (Arabic)',
    'settings.appearanceSettings': 'Appearance Settings',
    'settings.appearanceSettingsDesc': 'Customize the look and feel of your dashboard',
    'settings.theme': 'Theme',
    'settings.themeDesc': 'Choose your preferred theme',
    'settings.lightTheme': 'Light',
    'settings.darkTheme': 'Dark',
    'settings.autoTheme': 'Auto',
    'settings.saved': 'Settings Saved',
    'settings.savedDesc': 'Your settings have been updated successfully.',
    
    // Footer
    'footer.aboutUs': 'About Us',
    'footer.contactUs': 'Contact Us',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.termsOfService': 'Terms of Service',
    'footer.support': 'Support',
    'footer.help': 'Help',
    'footer.copyright': '© 2024 MWRD. All rights reserved.',
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.dashboard': 'لوحة التحكم',
    'nav.requests': 'الطلبات',
    'nav.offers': 'العروض',
    'nav.messages': 'الرسائل',
    'nav.profile': 'الملف الشخصي',
    'nav.admin': 'الإدارة',
    'nav.vendors': 'الموردين',
    'nav.projects': 'المشاريع',
    'nav.analytics': 'التحليلات',
    'nav.settings': 'الإعدادات',
    'nav.support': 'الدعم',
    'nav.logout': 'تسجيل الخروج',
    'nav.login': 'تسجيل الدخول',
    'nav.register': 'التسجيل',
    'nav.browseRequests': 'تصفح الطلبات',
    'nav.suppliers': 'الموردين',
    'nav.orders': 'الطلبيات',
    'nav.manageSubscription': 'إدارة الاشتراك',
    'nav.navigation': 'التنقل',
    
    // Common
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجح',
    'common.cancel': 'إلغاء',
    'common.save': 'حفظ',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.view': 'عرض',
    'common.create': 'إنشاء',
    'common.update': 'تحديث',
    'common.submit': 'إرسال',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.sort': 'ترتيب',
    'common.export': 'تصدير',
    'common.import': 'استيراد',
    'common.download': 'تحميل',
    'common.upload': 'رفع',
    'common.close': 'إغلاق',
    'common.open': 'فتح',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.confirm': 'تأكيد',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.finish': 'إنهاء',
    'common.start': 'بدء',
    'common.stop': 'إيقاف',
    'common.pause': 'إيقاف مؤقت',
    'common.resume': 'استئناف',
    'common.reset': 'إعادة تعيين',
    'common.clear': 'مسح',
    'common.refresh': 'تحديث',
    'common.reload': 'إعادة تحميل',
    'common.copy': 'نسخ',
    'common.paste': 'لصق',
    'common.cut': 'قص',
    'common.select': 'اختيار',
    'common.deselect': 'إلغاء الاختيار',
    'common.selectAll': 'اختيار الكل',
    'common.deselectAll': 'إلغاء اختيار الكل',
    'common.profile': 'الملف الشخصي',
    'common.signOut': 'تسجيل الخروج',
    'common.settings': 'الإعدادات',
    'common.viewAll': 'عرض الكل',
    'common.filterByStatus': 'تصفية حسب الحالة',
    'common.all': 'الكل',
    'common.pending': 'قيد الانتظار',
    'common.succeeded': 'نجح',
    'common.failed': 'فشل',
    'common.type': 'النوع',
    'common.of': 'من',
    'common.urgency': 'الأولوية',
    'common.urgent': 'عاجل',
    'common.high': 'عالي',
    'common.medium': 'متوسط',
    'common.low': 'منخفض',
    
    // Time formatting
    'time.now': 'الآن',
    'time.minutesAgo': 'منذ {minutes} دقيقة',
    'time.hoursAgo': 'منذ {hours} ساعة',
    'time.daysAgo': 'منذ {days} أيام',
    'time.minutes': 'دقائق',
    'time.hours': 'ساعات',
    'time.days': 'أيام',
    
    // Order status
    'orderStatus.pending': 'قيد الانتظار',
    'orderStatus.confirmed': 'مؤكد',
    'orderStatus.in_progress': 'قيد التنفيذ',
    'orderStatus.completed': 'مكتمل',
    'orderStatus.cancelled': 'ملغى',
    
    // App
    'app.name': 'مورد',
    'app.tagline': 'منصة المشتريات التجارية الذكية',
    'app.description': 'تواصل مع موردي الخدمات المعتمدين لاحتياجات المشتريات الخاصة بك',

    // Landing Footer - NEW ARABIC TRANSLATIONS
    'landing.footer.taglineText': 'حوّل عمليات المشتريات الخاصة بك من خلال منصتنا التجارية الذكية. تواصل مع الموردين المعتمدين وبسّط عمليات أعمالك.',
    'landing.footer.company': 'الشركة',
    'landing.footer.contactUsBtn': 'اتصل بنا',
    'landing.footer.blog': 'المدونة',
    'landing.footer.whyStart': 'لماذا تبدأ مع مورد',
    'landing.footer.whyMove': 'لماذا الانتقال إلى مورد',
    'landing.footer.pricingSection': 'الأسعار',
    'landing.footer.supportSection': 'الدعم',
    'landing.footer.support': 'المساعدة والدعم',
    'landing.footer.helpCenterLink': 'مركز المساعدة',
    'landing.footer.documentation': 'الوثائق',
    'landing.footer.systemStatus': 'حالة النظام',
    'landing.footer.privacyPolicy': 'سياسة الخصوصية',
    'landing.footer.termsOfService': 'الشروط والأحكام',
    'landing.footer.rights': 'جميع الحقوق محفوظة.',
    'landing.footer.followUs': 'تابعنا',
    
    // Analytics Dashboard
    'analytics.title': 'لوحة التحليلات',
    'analytics.trackActivity': 'تتبع نشاطك وأفكار الأداء',
    'analytics.last7Days': 'آخر 7 أيام',
    'analytics.last30Days': 'آخر 30 يوماً',
    'analytics.last90Days': 'آخر 90 يوماً',
    'analytics.totalRequests': 'إجمالي الطلبات',
    'analytics.activeChats': 'المحادثات النشطة',
    'analytics.responseRate': 'معدل الاستجابة',
    'analytics.avgResponseTime': 'متوسط وقت الاستجابة',
    'analytics.weeklyActivity': 'النشاط الأسبوعي',
    'analytics.weeklyActivityDesc': 'طلباتك ورسائلك وعروضك خلال آخر 7 أيام',
    'analytics.requestCategories': 'فئات الطلبات',
    'analytics.requestCategoriesDesc': 'توزيع طلباتك حسب الفئة',
    'analytics.performanceMetrics': 'مقاييس الأداء',
    'analytics.performanceMetricsDesc': 'تتبع تقدمك نحو الأهداف الرئيسية',
    'analytics.quickActions': 'إجراءات سريعة',
    'analytics.quickActionsDesc': 'إجراءات شائعة لتحسين أدائك',
    'analytics.completeProfile': 'إكمال الملف الشخصي',
    'analytics.addMissingInfo': 'إضافة المعلومات المفقودة',
    'analytics.respondToMessages': 'الرد على الرسائل',
    'analytics.pendingResponses': 'ردود معلقة',
    'analytics.createNewRequest': 'إنشاء طلب جديد',
    'analytics.findMoreSuppliers': 'العثور على المزيد من الموردين',
    'analytics.profileCompletion': 'اكتمال الملف الشخصي',
    'analytics.activeRequests': 'الطلبات النشطة',
    'analytics.vendorConnections': 'اتصالات المورد',
    'analytics.fromLastWeek': 'من الأسبوع الماضي',
    'analytics.manufacturing': 'التصنيع',
    'analytics.technology': 'التكنولوجيا',
    'analytics.logistics': 'اللوجستيات',
    'analytics.marketing': 'التسويق',
    'analytics.other': 'أخرى',
    'analytics.monday': 'الإثنين',
    'analytics.tuesday': 'الثلاثاء',
    'analytics.wednesday': 'الأربعاء',
    'analytics.thursday': 'الخميس',
    'analytics.friday': 'الجمعة',
    'analytics.saturday': 'السبت',
    'analytics.sunday': 'الأحد',
    'analytics.requests': 'الطلبات',
    'analytics.messages': 'الرسائل',
    'analytics.offers': 'العروض',
    'analytics.overview': 'نظرة عامة',
    'analytics.completedProjects': 'المشاريع المكتملة',
    'analytics.totalRevenue': 'إجمالي الإيرادات',
    'analytics.requestsOverTime': 'الطلبات عبر الزمن',
    'analytics.offersByCategory': 'العروض حسب الفئة',
    'analytics.topPerformingVendors': 'أفضل الموردين أداءً',
    'analytics.recentActivity': 'النشاط الأخير',
    'analytics.month': 'الشهر',
    'analytics.category': 'الفئة',
    'analytics.vendor': 'المورد',
    'analytics.revenue': 'الإيرادات',
    'analytics.projects': 'المشاريع',
    'analytics.noDataAvailable': 'لا توجد بيانات متاحة',
    'analytics.loadingData': 'جاري تحميل بيانات التحليلات...',
    'analytics.refreshData': 'تحديث البيانات',
    'analytics.exportData': 'تصدير البيانات',
    'analytics.dateRange': 'نطاق التاريخ',
    'analytics.customRange': 'نطاق مخصص',
    
    // Auth
    'auth.login': 'تسجيل الدخول',
    'auth.register': 'التسجيل',
    'auth.logout': 'تسجيل الخروج',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.confirmPassword': 'تأكيد كلمة المرور',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.rememberMe': 'تذكرني',
    'auth.loginSuccess': 'تم تسجيل الدخول بنجاح',
    'auth.loginError': 'فشل في تسجيل الدخول',
    'auth.registerSuccess': 'تم إنشاء الحساب بنجاح',
    'auth.registerError': 'فشل في التسجيل',
    'auth.logoutSuccess': 'تم تسجيل الخروج بنجاح',
    
    // Dashboard
    'dashboard.title': 'لوحة التحكم',
    'dashboard.welcome': 'مرحباً بك في مورد',
    'dashboard.overview': 'نظرة عامة',
    'dashboard.recentActivity': 'النشاط الأخير',
    'dashboard.quickActions': 'إجراءات سريعة',
    'dashboard.statistics': 'الإحصائيات',
    'dashboard.search': 'بحث...',
    'dashboard.findOpportunities': 'ابحث عن الفرص التجارية',
    'dashboard.completedProjects': 'المشاريع المكتملة',

    // Vendor Dashboard specific keys
    'vendor.welcome': 'مرحباً بك في لوحة المورد',
    'vendor.subtitle': 'إدارة عروضك وتصفح الطلبات وتنمية أعمالك',
    'vendor.totalOffers': 'إجمالي العروض',
    'vendor.acceptedOffers': 'العروض المقبولة',
    'vendor.pendingOffers': 'العروض المعلقة',
    'vendor.searchRequests': 'البحث في الطلبات المتاحة...',
    'vendor.filterByCategory': 'تصفية حسب الفئة',
    'vendor.availableRequests': 'الطلبات المتاحة',
    'vendor.submitOffer': 'تقديم عرض',
    'vendor.viewDetails': 'عرض التفاصيل',
    'vendor.submittedThisMonth': 'تم تقديمها هذا الشهر',
    'vendor.successRate': 'معدل النجاح',
    'vendor.awaitingClientResponse': 'في انتظار رد العميل',
    'vendor.successfullyWon': 'تم الفوز بها بنجاح',
    'vendor.inProgressCompleted': 'قيد التنفيذ والمكتملة',
    'vendor.winRate': 'معدل الفوز',
    'vendor.offersWon': 'عروض فائزة',
    'vendor.pendingReviews': 'مراجعات معلقة',
    'vendor.activeProjects': 'مشاريع نشطة',
    'vendor.findOpportunities': 'البحث عن الفرص',
    'vendor.filterDescription': 'تصفية والبحث عن طلبات الأسعار التي تناسب خبرتك',
    'vendor.opportunitiesFound': 'فرص متاحة',
    'vendor.availableOpportunities': 'الفرص المتاحة',
    'vendor.completeVerificationToSubmit': 'أكمل التحقق لتقديم العروض',
    'vendor.submitOffersToWin': 'قدم عروض للفوز بالمشاريع',
    'vendor.verificationRequired': 'التحقق مطلوب',
    'vendor.budget': 'الميزانية',
    'vendor.negotiable': 'قابل للتفاوض',
    'vendor.due': 'مستحق',
    'vendor.open': 'مفتوح',
    
    // Enhanced vendor dashboard keys
    'vendor.totalOffersDesc': 'تم تقديمها هذا الشهر',
    'vendor.winRateDesc': 'من {total} عرض تم الفوز بها',
    'vendor.pendingReviewsDesc': 'في انتظار رد العميل',
    'vendor.activeProjectsDesc': 'قيد التنفيذ والمكتملة',

    // Browse Requests
    'browseRequests.title': 'تصفح الطلبات',
    'browseRequests.subtitle': 'البحث عن طلبات المشتريات وتقديم العروض',
    'browseRequests.searchAndFilter': 'البحث والتصفية',
    'browseRequests.searchPlaceholder': 'البحث في الطلبات...',
    'browseRequests.filterByCategory': 'تصفية حسب الفئة',
    'browseRequests.filterDescription': 'ابحث عن الفرص المثالية لعملك',
    'browseRequests.noResults': 'لم يتم العثور على طلبات',
    'browseRequests.noResultsDesc': 'حاول تعديل معايير البحث',
    'browseRequests.budget': 'الميزانية',
    'browseRequests.deadline': 'الموعد النهائي',
    'browseRequests.posted': 'تاريخ النشر',
    'browseRequests.submitOffer': 'تقديم عرض',
    'browseRequests.viewDetails': 'عرض التفاصيل',
    
    // Requests
    'requests.title': 'الطلبات',
    'requests.create': 'إنشاء طلب',
    'requests.myRequests': 'طلباتي',
    'requests.allRequests': 'جميع الطلبات',
    'requests.pending': 'قيد الانتظار',
    'requests.approved': 'معتمد',
    'requests.rejected': 'مرفوض',
    'requests.inProgress': 'قيد التنفيذ',
    'requests.completed': 'مكتمل',
    
    // My Offers - NEW ARABIC TRANSLATIONS
    'myOffers.title': 'عروضي',
    'myOffers.subtitle': 'تتبع وإدارة عروضك المقدمة',
    'myOffers.noOffers': 'لا توجد عروض مقدمة',
    'myOffers.noOffersDesc': 'لم تقدم أي عروض بعد. تصفح الطلبات للبدء.',
    'myOffers.offerNumber': 'عرض',
    'myOffers.noDescription': 'لا يوجد وصف',
    'myOffers.price': 'السعر',
    'myOffers.priceNotSet': 'لم يتم تحديد السعر',
    'myOffers.deliveryTime': 'وقت التسليم',
    'myOffers.daysDelivery': 'أيام التسليم',
    'myOffers.submitted': 'تم التقديم',
    'myOffers.clientResponse': 'رد العميل',
    'myOffers.status.pending': 'قيد الانتظار',
    'myOffers.status.approved': 'مقبول',
    'myOffers.status.rejected': 'مرفوض',
    'myOffers.status.accepted': 'مقبول',

    // Offers
    'offers.title': 'إدارة العروض',
    'offers.subtitle.vendor': 'إدارة عروضك المقدمة للعملاء',
    'offers.subtitle.client': 'مراجعة والموافقة على العروض المقدمة',
    'offers.create': 'إنشاء عرض',
    'offers.myOffers': 'عروضي',
    'offers.allOffers': 'جميع العروض',
    'offers.received': 'مستلمة',
    'offers.sent': 'مرسلة',
    'offers.totalOffers': 'إجمالي العروض',
    'offers.status.approved': 'مقبول',
    'offers.status.rejected': 'مرفوض',
    'offers.status.pending': 'قيد المراجعة',
    'offers.searchPlaceholder': 'البحث في العروض...',
    'offers.offerStatus': 'حالة العرض',
    'offers.allStatus': 'جميع الحالات',
    'offers.compare': 'مقارنة',
    'offers.newOffer': 'عرض جديد',
    'offers.forRequest': 'للطلب:',
    'offers.vendor': 'المورد:',
    'offers.viewDetails': 'عرض التفاصيل',
    'offers.messageVendor': 'مراسلة المورد',
    'offers.accept': 'قبول',
    'offers.reject': 'رفض',
    'offers.noOffers': 'لا توجد عروض',
    'offers.noOffersDesc.search': 'لم يتم العثور على عروض تطابق معايير البحث',
    'offers.noOffersDesc.vendor': 'لم تقم بتقديم أي عروض بعد. ابدأ بإنشاء عرض جديد.',
    'offers.noOffersDesc.client': 'لم يتم تقديم عروض لطلباتك بعد.',
    'offers.days': 'أيام',
    'offers.selectOffers': 'اختر العروض للمقارنة',
    'offers.selectAll': 'اختيار الكل',
    'offers.deselectAll': 'إلغاء اختيار الكل',
    'offers.compareSelected': 'مقارنة المحدد',
    'offers.offersSelected': 'عروض محددة',
    'offers.price': 'السعر',
    'offers.deliveryTime': 'وقت التسليم',
    'offers.submittedOn': 'تم التقديم في',
    'offers.submittedBy': 'تم التقديم بواسطة',
    'offers.status': 'الحالة',
    
    // Messages
    'messages.title': 'الرسائل',
    'messages.newMessage': 'رسالة جديدة',
    'messages.compose': 'إنشاء',
    'messages.inbox': 'صندوق الوارد',
    'messages.sent': 'مرسلة',
    'messages.drafts': 'المسودات',
    'messages.trash': 'سلة المهملات',
    'messages.communicateWithSuppliers': 'تواصل مع الموردين والعملاء',
    'messages.searchConversations': 'البحث في المحادثات...',
    'messages.noMatchingConversations': 'لا توجد محادثات مطابقة',
    'messages.noConversations': 'لا توجد محادثات',
    'messages.tryDifferentSearch': 'جرب مصطلح بحث مختلف',
    'messages.startConversation': 'ابدأ محادثة من خلال الرد على عرض أو طلب',
    'messages.failedToLoadConversations': 'فشل في تحميل المحادثات',
    
    // Profile
    'profile.title': 'إعدادات الملف الشخصي',
    'profile.subtitle': 'إدارة معلومات حسابك وحالة التحقق',
    'profile.edit': 'تعديل الملف الشخصي',
    'profile.settings': 'إعدادات الملف الشخصي',
    'profile.personalInfo': 'المعلومات الشخصية',
    'profile.personalInfoDesc': 'تحديث تفاصيلك الشخصية ومعلومات الاتصال',
    'profile.companyInfo': 'معلومات الشركة',
    'profile.companyInfoDesc': 'تفاصيل الشركة والمعلومات التجارية',
    'profile.contactInfo': 'معلومات الاتصال',
    'profile.fullName': 'الاسم الكامل',
    'profile.email': 'البريد الإلكتروني',
    'profile.phone': 'الهاتف',
    'profile.role': 'الدور',
    'profile.address': 'العنوان',
    'profile.companyName': 'اسم الشركة',
    'profile.bio': 'وصف الشركة والخدمات',
    'profile.bioClient': 'وصف الشركة',
    'profile.bioPlaceholder': 'وصف شركتك وخدماتك وخبراتك...',
    'profile.bioPlaceholderClient': 'وصف شركتك وأعمالك...',
    'profile.portfolioUrl': 'رابط المحفظة',
    'profile.saveChanges': 'حفظ التغييرات',
    'profile.saving': 'جاري الحفظ...',
    'profile.serviceCategories': 'فئات الخدمات',
    'profile.serviceCategoriesDesc': 'اختر فئات الخدمات التي تقدمها. هذا يساعد العملاء في العثور عليك للطلبات ذات الصلة.',
    'profile.selectedCategories': 'الفئات المحددة:',
    'profile.saveCategories': 'حفظ الفئات',
    'profile.verification': 'التحقق',
    'profile.verificationRequirements': 'متطلبات التحقق',
    'profile.verificationDesc': 'كمورد، التحقق مطلوب للوصول إلى ميزات المناقصات وإدارة الطلبيات',
    'profile.accountSettings': 'إعدادات الحساب',
    'profile.accountSettingsDesc': 'إدارة تفضيلات حسابك وإعدادات الأمان',
    'profile.accountStatus': 'حالة الحساب',
    'profile.subscriptionPlan': 'خطة الاشتراك',
    'profile.memberSince': 'عضو منذ',
    'profile.verified': 'محقق',
    'profile.rejected': 'مرفوض',
    'profile.underReview': 'قيد المراجعة',
    'profile.pendingVerification': 'في انتظار التحقق',
    'profile.tabs.profile': 'الملف الشخصي',
    'profile.tabs.categories': 'الفئات',
    'profile.tabs.verification': 'التحقق',
    'profile.tabs.settings': 'الإعدادات',
    
    // Theme
    'theme.light': 'فاتح',
    'theme.dark': 'داكن',
    'theme.system': 'النظام',
    
    // Admin Panel
    'admin.panel': 'لوحة الإدارة',
    'admin.managementDashboard': 'لوحة إدارة النظام',
    'admin.adminVersion': 'نسخة الإدارة',
    'admin.adminUser': 'مستخدم إداري',
    'admin.searchPlaceholder': 'البحث في لوحة الإدارة...',
    'admin.notificationsDemo': 'إشعارات تجريبية',
    'searching': 'جاري البحث',
    
    // Admin Menu Items
    'admin.menu.dashboard': 'لوحة التحكم',
    'admin.menu.userManagement': 'إدارة المستخدمين',
    'admin.menu.allUsers': 'جميع المستخدمين',
    'admin.menu.advancedManagement': 'الإدارة المتقدمة',
    'admin.menu.userProfiles': 'ملفات المستخدمين',
    'admin.menu.financial': 'المالية',
    'admin.menu.financialDashboard': 'لوحة المالية',
    'admin.menu.transactions': 'المعاملات',
    'admin.menu.subscriptions': 'الاشتراكات',
    'admin.menu.analytics': 'التحليلات',
    'admin.menu.platformAnalytics': 'تحليلات المنصة',
    'admin.menu.userActivity': 'نشاط المستخدمين',
    'admin.menu.reports': 'التقارير',
    'admin.menu.contentManagement': 'إدارة المحتوى',
    'admin.menu.requestsApproval': 'اعتماد الطلبات',
    'admin.menu.offersManagement': 'إدارة العروض',
    'admin.menu.expertConsultations': 'الاستشارات الخبيرة',
    'admin.menu.system': 'النظام',
    'admin.menu.settings': 'الإعدادات',
    'admin.menu.themeDesign': 'تصميم النسق',
    'admin.menu.database': 'قاعدة البيانات',
    
    // Orders
    'orders.title': 'الطلبيات',
    'orders.subtitle': 'تتبع وإدارة طلبياتك',
    'orders.noOrders': 'لا توجد طلبيات',
    'orders.noOrdersDesc': 'ليس لديك أي طلبيات بعد. ابدأ بتقديم الطلبات أو العروض.',
    'orders.orderNumber': 'طلبية',
    'orders.noDescription': 'لا يوجد وصف متاح',
    'orders.amountNotSet': 'لم يتم تحديد المبلغ',
    'orders.created': 'تم الإنشاء',
    'orders.delivery': 'التسليم',
    'orders.viewDetails': 'عرض التفاصيل',
    
    // Settings
    'settings.title': 'الإعدادات',
    'settings.subtitle': 'إدارة تفضيلات حسابك والإعدادات',
    'settings.tabs.notifications': 'الإشعارات',
    'settings.tabs.security': 'الأمان',
    'settings.tabs.language': 'اللغة',
    'settings.tabs.appearance': 'المظهر',
    'settings.notificationPrefs': 'تفضيلات الإشعارات',
    'settings.notificationPrefsDesc': 'اختر كيفية تلقي الإشعارات',
    'settings.emailNotifications': 'إشعارات البريد الإلكتروني',
    'settings.emailNotificationsDesc': 'تلقي الإشعارات عبر البريد الإلكتروني',
    'settings.pushNotifications': 'الإشعارات المنبثقة',
    'settings.pushNotificationsDesc': 'تلقي الإشعارات المنبثقة في متصفحك',
    'settings.smsNotifications': 'إشعارات الرسائل القصيرة',
    'settings.smsNotificationsDesc': 'تلقي التحديثات المهمة عبر الرسائل القصيرة',
    'settings.marketingComms': 'الاتصالات التسويقية',
    'settings.marketingCommsDesc': 'تلقي التحديثات حول الميزات الجديدة والعروض',
    'settings.savePreferences': 'حفظ التفضيلات',
    'settings.securitySettings': 'إعدادات الأمان',
    'settings.securitySettingsDesc': 'إدارة أمان حسابك وكلمة المرور',
    'settings.currentPassword': 'كلمة المرور الحالية',
    'settings.newPassword': 'كلمة المرور الجديدة',
    'settings.confirmPassword': 'تأكيد كلمة المرور الجديدة',
    'settings.updatePassword': 'تحديث كلمة المرور',
    'settings.languagePrefs': 'تفضيلات اللغة',
    'settings.languagePrefsDesc': 'اختر لغتك المفضلة للواجهة',
    'settings.english': 'English',
    'settings.arabic': 'العربية (Arabic)',
    'settings.appearanceSettings': 'إعدادات المظهر',
    'settings.appearanceSettingsDesc': 'تخصيص مظهر وشكل لوحة التحكم',
    'settings.theme': 'النسق',
    'settings.themeDesc': 'اختر نسقك المفضل',
    'settings.lightTheme': 'فاتح',
    'settings.darkTheme': 'داكن',
    'settings.autoTheme': 'تلقائي',
    'settings.saved': 'تم حفظ الإعدادات',
    'settings.savedDesc': 'تم تحديث إعداداتك بنجاح.',
    
    // Footer
    'footer.aboutUs': 'من نحن',
    'footer.contactUs': 'اتصل بنا',
    'footer.privacyPolicy': 'سياسة الخصوصية',
    'footer.termsOfService': 'شروط الخدمة',
    'footer.support': 'الدعم',
    'footer.help': 'المساعدة',
    'footer.copyright': '© 2024 مورد. جميع الحقوق محفوظة.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
