import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // App name and slogan
    'app.name': 'Supplify',
    'app.slogan': 'All Event Needs in One Place',
    // Language
    'language': 'en',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.requests': 'Service Requests',
    'nav.offers': 'My Offers',
    'nav.suppliers': 'Suppliers',
    'nav.profile': 'Profile',
    'nav.admin': 'Admin Panel',
    'nav.home': 'Home',
    'nav.pricing': 'Pricing',
    'nav.consultation': 'Expert Consultation',
    
    // Common
    'common.submit': 'Submit',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.pending': 'Pending',
    'common.accepted': 'Accepted',
    'common.rejected': 'Rejected',
    'common.completed': 'Completed',
    'common.active': 'Active',
    'common.offers': 'offers',
    'common.viewAll': 'View All',
    'common.recent': 'Recent',
    'common.createNew': 'Create New',
    'common.profile': 'Profile',
    'common.settings': 'Settings',
    'common.signOut': 'Sign out',
    'common.notifications': 'Notifications',
    'common.search': 'Search...',
    
    // Auth
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.logout': 'Logout',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.company': 'Company Name',
    'auth.role': 'Role',
    'auth.client': 'Client',
    'auth.supplier': 'Supplier',
    'auth.welcomeBack': 'Welcome back!',
    'auth.welcomeToSupplify': 'Welcome to Supplify!',
    'auth.signInDescription': 'Sign in to your account or create a new one',
    'auth.enterEmail': 'Enter your email',
    'auth.enterPassword': 'Enter your password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.enterCompanyName': 'Enter your company name',
    'auth.signInButton': 'Sign In',
    'auth.createAccountButton': 'Create Account',
    'auth.showPassword': 'Show password',
    'auth.hidePassword': 'Hide password',
    
    // Dashboard
    'dashboard.welcome': 'Welcome to Supplify',
    'dashboard.subtitle': 'Connect with vetted service providers for your events',
    'dashboard.createRequest': 'Create Service Request',
    'dashboard.search': 'Search...',
    'dashboard.viewRequests': 'View My Requests',
    'dashboard.browseSuppliers': 'Browse Suppliers',
    'dashboard.createOffer': 'Create New Offer',
    'dashboard.recentOffers': 'Recent Offers',
    'dashboard.recentRequests': 'Recent Service Requests',
    'dashboard.totalRequests': 'Total Requests',
    'dashboard.activeOffers': 'Active Offers',
    'dashboard.completedProjects': 'Completed Projects',
    'dashboard.totalEarnings': 'Total Earnings',
    
    // Requests
    'request.create': 'Create New Request',
    'request.title': 'Service Request',
    'request.category': 'Service Category',
    'request.description': 'Description',
    'request.budget': 'Budget Range',
    'request.deadline': 'Event Date',
    'request.city': 'City',
    
    // Categories
    'category.booth': 'Booth Stands',
    'category.printing': 'Printing',
    'category.furniture': 'Furniture',
    'category.equipment': 'Equipment',
    'category.giveaways': 'Giveaways',
    'category.logistics': 'Logistics',
    'category.avl': 'AVL (Audio-Visual-Lighting)',
    'category.hospitality': 'Hospitality',
    'category.manpower': 'Manpower',
    'category.portacabin': 'Porta Cabin (WC/Office)',
    'category.registration': 'Registration',
    'category.media': 'Media (Photo/Video/Drone)',
    'category.carpets': 'Carpets',
    'category.flowers': 'Flowers',

    // Terms and Conditions
    'termsTitle': 'Terms and Conditions',
    'termsLastUpdated': 'Last updated: January 1, 2024',
    'termsAcceptanceTitle': '1. Acceptance of Terms',
    'termsAcceptanceContent': 'By accessing and using Supplify platform, you accept and agree to be bound by the terms and provision of this agreement.',
    'termsServicesTitle': '2. Description of Services',
    'termsServicesContent': 'Supplify provides a digital platform that connects event organizers with suppliers and service providers. Our services include:',
    'termsServicesItem1': 'Marketplace for events supplies and services',
    'termsServicesItem2': 'Request and quotation management system',
    'termsServicesItem3': 'Supplier verification and rating system',
    'termsServicesItem4': 'Payment processing and order management',
    'termsAccountTitle': '3. User Accounts',
    'termsAccountContent': 'To access certain features of our platform, you must create an account. You are responsible for:',
    'termsAccountItem1': 'Maintaining the confidentiality of your account credentials',
    'termsAccountItem2': 'All activities that occur under your account',
    'termsAccountItem3': 'Providing accurate and up-to-date information',
    'termsPaymentTitle': '4. Payment Terms',
    'termsPaymentContent': 'Payment terms are established between buyers and suppliers. Supplify may facilitate payments but is not responsible for payment disputes between parties.',
    'termsProhibitedTitle': '5. Prohibited Uses',
    'termsProhibitedContent': 'You may not use our platform for any unlawful purpose or to solicit others to perform unlawful acts. Prohibited activities include:',
    'termsProhibitedItem1': 'Fraudulent or misleading activities',
    'termsProhibitedItem2': 'Violating any local, state, national, or international law',
    'termsProhibitedItem3': 'Transmitting any material that is abusive, harassing, or threatening',
    'termsProhibitedItem4': 'Attempting to gain unauthorized access to our systems',
    'termsIntellectualTitle': '6. Intellectual Property Rights',
    'termsIntellectualContent': 'The platform and its original content, features, and functionality are owned by Supplify and are protected by international copyright, trademark, patent, trade secret, and other intellectual property laws.',
    'termsTerminationTitle': '7. Termination',
    'termsTerminationContent': 'We may terminate or suspend your account and bar access to the platform immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever.',
    'termsLimitationTitle': '8. Limitation of Liability',
    'termsLimitationContent': 'In no event shall Supplify, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential, or punitive damages.',
    'termsGoverningTitle': '9. Governing Law',
    'termsGoverningContent': 'These Terms shall be interpreted and governed by the laws of the Kingdom of Saudi Arabia, without regard to its conflict of law provisions.',
    'termsChangesTitle': '10. Changes to Terms',
    'termsChangesContent': 'We reserve the right to modify or replace these Terms at any time. If a revision is material, we will provide at least 30 days notice prior to any new terms taking effect.',
    'termsContactTitle': '11. Contact Information',
    'termsContactContent': 'If you have any questions about these Terms and Conditions, please contact us:',
    'termsContactAddress': 'Address: Riyadh, Kingdom of Saudi Arabia',

    // Privacy Policy
    'privacyTitle': 'Privacy Policy',
    'privacyLastUpdated': 'Last updated: January 1, 2024',
    'privacyIntroTitle': '1. Introduction',
    'privacyIntroContent': 'Supplify ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our platform.',
    'privacyCollectionTitle': '2. Information We Collect',
    'privacyCollectionContent': 'We collect information you provide directly to us, information we collect automatically, and information from third parties:',
    'privacyPersonalInfoTitle': 'Personal Information:',
    'privacyPersonalInfoItem1': 'Name, email address, phone number',
    'privacyPersonalInfoItem2': 'Profile information and preferences',
    'privacyPersonalInfoItem3': 'Payment information (processed securely)',
    'privacyPersonalInfoItem4': 'Communication records and support requests',
    'privacyBusinessInfoTitle': 'Business Information:',
    'privacyBusinessInfoItem1': 'Company name, address, and business license',
    'privacyBusinessInfoItem2': 'Service offerings and product catalogs',
    'privacyBusinessInfoItem3': 'Transaction history and performance metrics',
    'privacyTechnicalInfoTitle': 'Technical Information:',
    'privacyTechnicalInfoItem1': 'IP address, browser type, and device information',
    'privacyTechnicalInfoItem2': 'Usage data and platform interactions',
    'privacyTechnicalInfoItem3': 'Cookies and similar tracking technologies',
    'privacyUsageTitle': '3. How We Use Your Information',
    'privacyUsageContent': 'We use the information we collect to:',
    'privacyUsageItem1': 'Provide, maintain, and improve our services',
    'privacyUsageItem2': 'Process transactions and send related information',
    'privacyUsageItem3': 'Send technical notices, updates, and support messages',
    'privacyUsageItem4': 'Respond to your comments and questions',
    'privacyUsageItem5': 'Monitor and analyze trends, usage, and activities',
    'privacySharingTitle': '4. Information Sharing',
    'privacySharingContent': 'We may share your information in the following situations:',
    'privacySharingItem1': 'With suppliers and customers to facilitate transactions',
    'privacySharingItem2': 'With service providers who assist in our operations',
    'privacySharingItem3': 'To comply with legal obligations',
    'privacySharingItem4': 'With your consent or at your direction',
    'privacySecurityTitle': '5. Data Security',
    'privacySecurityContent': 'We implement appropriate technical and organizational security measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction.',
    'privacyRetentionTitle': '6. Data Retention',
    'privacyRetentionContent': 'We retain your information for as long as necessary to provide our services, comply with legal obligations, resolve disputes, and enforce our agreements.',
    'privacyRightsTitle': '7. Your Rights',
    'privacyRightsContent': 'Depending on your location, you may have certain rights regarding your personal information:',
    'privacyRightsItem1': 'Access and receive a copy of your personal information',
    'privacyRightsItem2': 'Rectify inaccurate or incomplete information',
    'privacyRightsItem3': 'Delete your personal information',
    'privacyRightsItem4': 'Restrict or object to processing',
    'privacyRightsItem5': 'Data portability',
    'privacyCookiesTitle': '8. Cookies and Tracking',
    'privacyCookiesContent': 'We use cookies and similar tracking technologies to collect and track information and to improve and analyze our service. You can control cookies through your browser settings.',
    'privacyChangesTitle': '9. Changes to Privacy Policy',
    'privacyChangesContent': 'We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date.',
    'privacyContactTitle': '10. Contact Us',
    'privacyContactContent': 'If you have any questions about this Privacy Policy, please contact us:',
    'privacyContactAddress': 'Address: Riyadh, Kingdom of Saudi Arabia',
  },
  ar: {
    // App name and slogan
    'app.name': 'سبلايفي',
    'app.slogan': 'جميع احتياجات الفعاليات في مكان واحد',
    // Language
    'language': 'ar',
    // Navigation
    'nav.dashboard': 'لوحة التحكم',
    'nav.requests': 'طلبات الخدمة',
    'nav.offers': 'عروضي',
    'nav.suppliers': 'مقدمو الخدمات',
    'nav.profile': 'الملف الشخصي',
    'nav.admin': 'لوحة الإدارة',
    'nav.home': 'الرئيسية',
    'nav.pricing': 'الأسعار',
    'nav.consultation': 'استشارة خبير',
    
    // Common
    'common.submit': 'إرسال',
    'common.cancel': 'إلغاء',
    'common.save': 'حفظ',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.view': 'عرض',
    'common.pending': 'قيد الانتظار',
    'common.accepted': 'مقبول',
    'common.rejected': 'مرفوض',
    'common.completed': 'مكتمل',
    'common.active': 'نشط',
    'common.offers': 'عروض',
    'common.viewAll': 'عرض الكل',
    'common.recent': 'الحديث',
    'common.createNew': 'إنشاء جديد',
    'common.profile': 'الملف الشخصي',
    'common.settings': 'الإعدادات',
    'common.signOut': 'تسجيل الخروج',
    'common.notifications': 'الإشعارات',
    'common.search': 'بحث...',
    
    // Auth
    'auth.login': 'تسجيل الدخول',
    'auth.register': 'إنشاء حساب',
    'auth.logout': 'تسجيل الخروج',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.company': 'اسم الشركة',
    'auth.role': 'الدور',
    'auth.client': 'عميل',
    'auth.supplier': 'مقدم خدمة',
    'auth.welcomeBack': 'مرحباً بك مرة أخرى!',
    'auth.welcomeToSupplify': 'مرحباً بك في سبلفاي!',
    'auth.signInDescription': 'سجل دخولك أو أنشئ حساباً جديداً',
    'auth.enterEmail': 'أدخل بريدك الإلكتروني',
    'auth.enterPassword': 'أدخل كلمة المرور',
    'auth.confirmPassword': 'تأكيد كلمة المرور',
    'auth.enterCompanyName': 'أدخل اسم شركتك',
    'auth.signInButton': 'تسجيل الدخول',
    'auth.createAccountButton': 'إنشاء حساب',
    'auth.showPassword': 'إظهار كلمة المرور',
    'auth.hidePassword': 'إخفاء كلمة المرور',
    
    // Dashboard
    'dashboard.welcome': 'مرحباً بك في سبلفاي',
    'dashboard.subtitle': 'تواصل مع مقدمي الخدمات المعتمدين لفعالياتك',
    'dashboard.createRequest': 'إنشاء طلب خدمة',
    'dashboard.search': 'بحث...',
    'dashboard.viewRequests': 'عرض طلباتي',
    'dashboard.browseSuppliers': 'تصفح مقدمي الخدمات',
    'dashboard.createOffer': 'إنشاء عرض جديد',
    'dashboard.recentOffers': 'العروض الحديثة',
    'dashboard.recentRequests': 'طلبات الخدمة الحديثة',
    'dashboard.totalRequests': 'إجمالي الطلبات',
    'dashboard.activeOffers': 'العروض النشطة',
    'dashboard.completedProjects': 'المشاريع المكتملة',
    'dashboard.totalEarnings': 'إجمالي الأرباح',
    
    // Approval system
    'approval.pending': 'قيد المراجعة',
    'approval.approved': 'موافق عليه',
    'approval.rejected': 'مرفوض',
    'approval.approve': 'موافقة',
    'approval.reject': 'رفض',
    'approval.notes': 'ملاحظات الموافقة',
    'approval.addNotes': 'أضف ملاحظات حول قرار الموافقة...',
    'approval.processedOn': 'تمت المعالجة في:',
    'approval.approvalWorkflow': 'سير عمل الموافقات',
    'approval.requestApproval': 'موافقة الطلبات',
    'approval.offerApproval': 'موافقة العروض',
    
    // Status labels
    'status.pending': 'قيد الانتظار',
    'status.inProgress': 'قيد التنفيذ',
    'status.completed': 'مكتمل',
    'status.cancelled': 'ملغي',
    'status.open': 'مفتوح',
    'status.closed': 'مغلق',
    
    // Real-time features
    'realtime.connected': 'متصل',
    'realtime.disconnected': 'غير متصل',
    'realtime.newNotification': 'إشعار جديد',
    'realtime.updating': 'جاري التحديث...',
    
    // Requests
    'request.create': 'إنشاء طلب جديد',
    'request.title': 'طلب الخدمة',
    'request.category': 'فئة الخدمة',
    'request.description': 'الوصف',
    'request.budget': 'نطاق الميزانية',
    'request.deadline': 'تاريخ الفعالية',
    'request.city': 'المدينة',
    
    // Categories
    'category.booth': 'أكشاك العرض',
    'category.printing': 'الطباعة',
    'category.furniture': 'الأثاث',
    'category.equipment': 'المعدات',
    'category.giveaways': 'الهدايا الترويجية',
    'category.logistics': 'اللوجستيات',
    'category.avl': 'الصوت والصورة والإضاءة',
    'category.hospitality': 'الضيافة',
    'category.manpower': 'العمالة',
    'category.portacabin': 'المقاصف المحمولة (دورات مياه/مكاتب)',
    'category.registration': 'التسجيل',
    'category.media': 'الإعلام (تصوير/فيديو/طائرة مسيرة)',
    'category.carpets': 'السجاد',
    'category.flowers': 'الزهور',

    // Terms and Conditions (Arabic)
    'termsTitle': 'الشروط والأحكام',
    'termsLastUpdated': 'آخر تحديث: 1 يناير 2024',
    'termsAcceptanceTitle': '1. قبول الشروط',
    'termsAcceptanceContent': 'باستخدام منصة سبلفاي، فإنك توافق على الالتزام بشروط وأحكام هذه الاتفاقية.',
    'termsServicesTitle': '2. وصف الخدمات',
    'termsServicesContent': 'تقدم سبلفاي منصة رقمية تربط منظمي الفعاليات بالموردين ومقدمي الخدمات. تشمل خدماتنا:',
    'termsServicesItem1': 'سوق لوازم وخدمات الفعاليات',
    'termsServicesItem2': 'نظام إدارة الطلبات والعروض',
    'termsServicesItem3': 'نظام التحقق وتقييم الموردين',
    'termsServicesItem4': 'معالجة المدفوعات وإدارة الطلبات',
    'termsAccountTitle': '3. حسابات المستخدمين',
    'termsAccountContent': 'للوصول إلى ميزات معينة في منصتنا، يجب إنشاء حساب. أنت مسؤول عن:',
    'termsAccountItem1': 'الحفاظ على سرية بيانات حسابك',
    'termsAccountItem2': 'جميع الأنشطة التي تحدث تحت حسابك',
    'termsAccountItem3': 'تقديم معلومات دقيقة ومحدثة',
    'termsPaymentTitle': '4. شروط الدفع',
    'termsPaymentContent': 'يتم تحديد شروط الدفع بين المشترين والموردين. قد تسهل سبلفاي المدفوعات لكنها غير مسؤولة عن نزاعات الدفع بين الأطراف.',
    'termsProhibitedTitle': '5. الاستخدامات المحظورة',
    'termsProhibitedContent': 'لا يجوز استخدام منصتنا لأي غرض غير قانوني أو لحث الآخرين على أداء أعمال غير قانونية. تشمل الأنشطة المحظورة:',
    'termsProhibitedItem1': 'الأنشطة الاحتيالية أو المضللة',
    'termsProhibitedItem2': 'انتهاك أي قانون محلي أو إقليمي أو وطني أو دولي',
    'termsProhibitedItem3': 'نقل أي مادة مسيئة أو مضايقة أو مهددة',
    'termsProhibitedItem4': 'محاولة الحصول على وصول غير مصرح به لأنظمتنا',
    'termsIntellectualTitle': '6. حقوق الملكية الفكرية',
    'termsIntellectualContent': 'المنصة ومحتواها الأصلي وميزاتها ووظائفها مملوكة لسبلفاي ومحمية بموجب قوانين حقوق النشر والعلامات التجارية والبراءات والأسرار التجارية والملكية الفكرية الدولية.',
    'termsTerminationTitle': '7. الإنهاء',
    'termsTerminationContent': 'يجوز لنا إنهاء أو تعليق حسابك ومنع الوصول إلى المنصة فوراً، دون إشعار مسبق أو مسؤولية، وفقاً لتقديرنا الوحيد، لأي سبب كان.',
    'termsLimitationTitle': '8. تحديد المسؤولية',
    'termsLimitationContent': 'في أي حال من الأحوال لن تكون سبلفاي، أو مديريها أو موظفيها أو شركاؤها أو وكلاؤها أو مورديها أو شركاؤها، مسؤولين عن أي أضرار غير مباشرة أو عرضية أو خاصة أو تبعية أو عقابية.',
    'termsGoverningTitle': '9. القانون الحاكم',
    'termsGoverningContent': 'تفسر هذه الشروط وتحكم بموجب قوانين المملكة العربية السعودية، دون اعتبار لأحكام تنازع القوانين.',
    'termsChangesTitle': '10. تغييرات الشروط',
    'termsChangesContent': 'نحتفظ بالحق في تعديل أو استبدال هذه الشروط في أي وقت. إذا كان التعديل جوهرياً، فسنقدم إشعاراً لمدة 30 يوماً على الأقل قبل سريان أي شروط جديدة.',
    'termsContactTitle': '11. معلومات الاتصال',
    'termsContactContent': 'إذا كان لديك أي أسئلة حول هذه الشروط والأحكام، يرجى الاتصال بنا:',
    'termsContactAddress': 'العنوان: الرياض، المملكة العربية السعودية',

    // Privacy Policy (Arabic)
    'privacyTitle': 'سياسة الخصوصية',
    'privacyLastUpdated': 'آخر تحديث: 1 يناير 2024',
    'privacyIntroTitle': '1. مقدمة',
    'privacyIntroContent': 'سبلفاي ("نحن" أو "منصتنا" أو "لنا") ملتزمون بحماية خصوصيتك. تشرح سياسة الخصوصية هذه كيفية جمعنا واستخدامنا والكشف عن معلوماتك وحمايتها عند استخدام منصتنا.',
    'privacyCollectionTitle': '2. المعلومات التي نجمعها',
    'privacyCollectionContent': 'نجمع المعلومات التي تقدمها لنا مباشرة، والمعلومات التي نجمعها تلقائياً، والمعلومات من أطراف ثالثة:',
    'privacyPersonalInfoTitle': 'المعلومات الشخصية:',
    'privacyPersonalInfoItem1': 'الاسم وعنوان البريد الإلكتروني ورقم الهاتف',
    'privacyPersonalInfoItem2': 'معلومات الملف الشخصي والتفضيلات',
    'privacyPersonalInfoItem3': 'معلومات الدفع (تتم معالجتها بأمان)',
    'privacyPersonalInfoItem4': 'سجلات التواصل وطلبات الدعم',
    'privacyBusinessInfoTitle': 'المعلومات التجارية:',
    'privacyBusinessInfoItem1': 'اسم الشركة والعنوان ورخصة العمل',
    'privacyBusinessInfoItem2': 'عروض الخدمات وكتالوجات المنتجات',
    'privacyBusinessInfoItem3': 'سجل المعاملات ومقاييس الأداء',
    'privacyTechnicalInfoTitle': 'المعلومات التقنية:',
    'privacyTechnicalInfoItem1': 'عنوان IP ونوع المتصفح ومعلومات الجهاز',
    'privacyTechnicalInfoItem2': 'بيانات الاستخدام وتفاعلات المنصة',
    'privacyTechnicalInfoItem3': 'ملفات تعريف الارتباط وتقنيات التتبع المماثلة',
    'privacyUsageTitle': '3. كيف نستخدم معلوماتك',
    'privacyUsageContent': 'نستخدم المعلومات التي نجمعها من أجل:',
    'privacyUsageItem1': 'تقديم وصيانة وتحسين خدماتنا',
    'privacyUsageItem2': 'معالجة المعاملات وإرسال المعلومات ذات الصلة',
    'privacyUsageItem3': 'إرسال الإشعارات التقنية والتحديثات ورسائل الدعم',
    'privacyUsageItem4': 'الرد على تعليقاتك وأسئلتك',
    'privacyUsageItem5': 'مراقبة وتحليل الاتجاهات والاستخدام والأنشطة',
    'privacySharingTitle': '4. مشاركة المعلومات',
    'privacySharingContent': 'قد نشارك معلوماتك في الحالات التالية:',
    'privacySharingItem1': 'مع الموردين والعملاء لتسهيل المعاملات',
    'privacySharingItem2': 'مع مقدمي الخدمات الذين يساعدون في عملياتنا',
    'privacySharingItem3': 'للامتثال للالتزامات القانونية',
    'privacySharingItem4': 'بموافقتك أو بتوجيه منك',
    'privacySecurityTitle': '5. أمان البيانات',
    'privacySecurityContent': 'نطبق تدابير الأمان التقنية والتنظيمية المناسبة لحماية معلوماتك الشخصية من الوصول غير المصرح به أو التغيير أو الكشف أو التدمير.',
    'privacyRetentionTitle': '6. الاحتفاظ بالبيانات',
    'privacyRetentionContent': 'نحتفظ بمعلوماتك للمدة اللازمة لتقديم خدماتنا والامتثال للالتزامات القانونية وحل النزاعات وإنفاذ اتفاقياتنا.',
    'privacyRightsTitle': '7. حقوقك',
    'privacyRightsContent': 'اعتماداً على موقعك، قد يكون لك حقوق معينة فيما يتعلق بمعلوماتك الشخصية:',
    'privacyRightsItem1': 'الوصول إلى معلوماتك الشخصية والحصول على نسخة منها',
    'privacyRightsItem2': 'تصحيح المعلومات غير الدقيقة أو غير المكتملة',
    'privacyRightsItem3': 'حذف معلوماتك الشخصية',
    'privacyRightsItem4': 'تقييد أو الاعتراض على المعالجة',
    'privacyRightsItem5': 'قابلية نقل البيانات',
    'privacyCookiesTitle': '8. ملفات تعريف الارتباط والتتبع',
    'privacyCookiesContent': 'نستخدم ملفات تعريف الارتباط وتقنيات التتبع المماثلة لجمع وتتبع المعلومات ولتحسين وتحليل خدمتنا. يمكنك التحكم في ملفات تعريف الارتباط من خلال إعدادات متصفحك.',
    'privacyChangesTitle': '9. تغييرات سياسة الخصوصية',
    'privacyChangesContent': 'قد نحدث سياسة الخصوصية هذه من وقت لآخر. سنخطرك بأي تغييرات عن طريق نشر سياسة الخصوصية الجديدة في هذه الصفحة وتحديث تاريخ "آخر تحديث".',
    'privacyContactTitle': '10. اتصل بنا',
    'privacyContactContent': 'إذا كان لديك أي أسئلة حول سياسة الخصوصية هذه، يرجى الاتصال بنا:',
    'privacyContactAddress': 'العنوان: الرياض، المملكة العربية السعودية',
    
    // Admin translations (Arabic)
    'adminPanel': 'لوحة الإدارة',
    'managementDashboard': 'لوحة التحكم الإدارية',
    'backToSite': 'العودة للموقع',
    'searchPlaceholder': 'البحث في لوحة الإدارة...',
    'searching': 'جاري البحث',
    'quickActions': 'إجراءات سريعة',
    'addNewUser': 'إضافة مستخدم جديد',
    'reviewRequests': 'مراجعة الطلبات',
    'viewAnalytics': 'عرض التحليلات',
    'adminUser': 'مستخدم إداري',
    'adminSettings': 'إعدادات الإدارة',
    'adminVersion': 'لوحة الإدارة الإصدار 2.0',
    'dashboard': 'لوحة التحكم',
    'usermanagement': 'إدارة المستخدمين',
    'allusers': 'جميع المستخدمين',
    'advancedmanagement': 'إدارة متقدمة',
    'userprofiles': 'ملفات المستخدمين',
    'financial': 'المالية',
    'transactions': 'المعاملات',
    'subscriptions': 'الاشتراكات',
    'analytics': 'التحليلات',
    'platformanalytics': 'تحليلات المنصة',
    'useractivity': 'نشاط المستخدمين',
    'reports': 'التقارير',
    'contentmanagement': 'إدارة المحتوى',
    'requestsapproval': 'موافقة الطلبات',
    'offersmanagement': 'إدارة العروض',
    'expertconsultations': 'استشارات الخبراء',
    'system': 'النظام',
    'themedesign': 'التصميم والمظهر',
    'database': 'قاعدة البيانات',
    'admin': 'مدير',
    'client': 'عميل',
    'supplier': 'مورد',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ar');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ar' : 'en');
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  // Set document dir attribute for proper RTL support
  React.useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.className = language === 'ar' ? 'font-arabic' : '';
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      <div dir={language === 'ar' ? 'rtl' : 'ltr'} className={language === 'ar' ? 'font-arabic' : ''}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};