import { faker } from '@faker-js/faker';

export const createMockUser = (overrides = {}) => ({
  id: faker.string.uuid(),
  email: faker.internet.email(),
  full_name: faker.person.fullName(),
  role: 'client' as const,
  status: 'approved' as const,
  verification_status: 'approved' as const,
  created_at: new Date().toISOString(),
  ...overrides,
});

export const createMockRequest = (clientId: string, overrides = {}) => ({
  id: faker.string.uuid(),
  client_id: clientId,
  title: faker.commerce.productName(),
  description: faker.commerce.productDescription(),
  category: 'IT Services',
  budget_min: 1000,
  budget_max: 5000,
  deadline: faker.date.future().toISOString(),
  status: 'open' as const,
  urgency: 'medium' as const,
  created_at: new Date().toISOString(),
  ...overrides,
});

export const createMockOffer = (requestId: string, vendorId: string, overrides = {}) => ({
  id: faker.string.uuid(),
  request_id: requestId,
  vendor_id: vendorId,
  title: faker.commerce.productName(),
  description: faker.commerce.productDescription(),
  price: faker.number.int({ min: 1000, max: 10000 }),
  currency: 'SAR',
  delivery_time_days: faker.number.int({ min: 7, max: 30 }),
  status: 'pending' as const,
  created_at: new Date().toISOString(),
  ...overrides,
});

export const createMockKYCSubmission = (userId: string, overrides = {}) => ({
  id: faker.string.uuid(),
  user_id: userId,
  focal_first_name: faker.person.firstName(),
  focal_last_name: faker.person.lastName(),
  focal_designation: 'CEO',
  focal_email: faker.internet.email(),
  focal_phone: '+966501234567',
  company_legal_name: faker.company.name(),
  cr_number: faker.string.numeric(10),
  cr_issuing_city: 'Riyadh',
  cr_issuing_date: '2020-01-01',
  cr_validity_date: '2025-01-01',
  cr_document_url: 'https://example.com/cr.pdf',
  vat_number: faker.string.numeric(15),
  vat_certificate_url: 'https://example.com/vat.pdf',
  address_city: 'Riyadh',
  address_area: 'Olaya',
  address_postal_code: '12345',
  address_street_name: 'King Fahd Road',
  address_building_number: '123',
  address_certificate_url: 'https://example.com/address.pdf',
  organization_type: 'LLC',
  nature_of_business: 'Technology',
  signatory_first_name: faker.person.firstName(),
  signatory_last_name: faker.person.lastName(),
  signatory_designation: 'CEO',
  signatory_email: faker.internet.email(),
  signatory_phone: '+966501234567',
  account_type: 'cash' as const,
  service_categories: ['IT Services'],
  submission_status: 'draft' as const,
  created_at: new Date().toISOString(),
  ...overrides,
});
