import { Node, Edge, MarkerType } from '@xyflow/react';
import { 
  UserPlus, 
  Layout, 
  FileText, 
  Users, 
  CheckCircle, 
  BarChart3,
  ShoppingCart,
  Handshake,
  Clock,
  Shield
} from 'lucide-react';

export const initialNodes: Node[] = [
  // Main user journey steps
  {
    id: 'step-0',
    type: 'step',
    position: { x: 50, y: 50 },
    data: {
      stepNumber: 0,
      titleEn: 'Welcome to MWRD',
      titleAr: 'مرحباً بك في مورد',
      descEn: 'Your complete procurement management platform',
      descAr: 'منصتك الكاملة لإدارة المشتريات',
      icon: Layout,
      isActive: false,
      isCompleted: false,
    },
  },
  {
    id: 'step-1',
    type: 'step',
    position: { x: 50, y: 200 },
    data: {
      stepNumber: 1,
      titleEn: 'Create an Account',
      titleAr: 'إنشاء حساب',
      descEn: 'Quick and easy registration process',
      descAr: 'عملية تسجيل سريعة وسهلة',
      icon: UserPlus,
      isActive: false,
      isCompleted: false,
    },
  },
  {
    id: 'step-2',
    type: 'step',
    position: { x: 50, y: 350 },
    data: {
      stepNumber: 2,
      titleEn: 'Dashboard Overview',
      titleAr: 'نظرة عامة على لوحة التحكم',
      descEn: 'Your centralized control center',
      descAr: 'مركز التحكم المركزي الخاص بك',
      icon: Layout,
      isActive: false,
      isCompleted: false,
    },
  },
  {
    id: 'step-3',
    type: 'step',
    position: { x: 400, y: 200 },
    data: {
      stepNumber: 3,
      titleEn: 'Create Service Request',
      titleAr: 'إنشاء طلب خدمة',
      descEn: 'Request any event service you need',
      descAr: 'اطلب أي خدمة فعاليات تحتاجها',
      icon: FileText,
      isActive: false,
      isCompleted: false,
    },
  },
  {
    id: 'step-4',
    type: 'step',
    position: { x: 400, y: 350 },
    data: {
      stepNumber: 4,
      titleEn: 'Browse Suppliers',
      titleAr: 'تصفح المورديين',
      descEn: 'Find vetted suppliers for your needs',
      descAr: 'ابحث عن موردين معتمدين لاحتياجاتك',
      icon: Users,
      isActive: false,
      isCompleted: false,
    },
  },
  {
    id: 'step-5',
    type: 'step',
    position: { x: 750, y: 200 },
    data: {
      stepNumber: 5,
      titleEn: 'Manage Approvals',
      titleAr: 'إدارة الموافقات',
      descEn: 'Streamlined approval workflows',
      descAr: 'سير عمل موافقات مبسط',
      icon: CheckCircle,
      isActive: false,
      isCompleted: false,
    },
  },
  {
    id: 'step-6',
    type: 'step',
    position: { x: 750, y: 350 },
    data: {
      stepNumber: 6,
      titleEn: 'Track Progress',
      titleAr: 'تتبع التقدم',
      descEn: 'Monitor your orders in real-time',
      descAr: 'راقب طلباتك في الوقت الفعلي',
      icon: BarChart3,
      isActive: false,
      isCompleted: false,
    },
  },
  
  // Feature nodes
  {
    id: 'feature-1',
    type: 'feature',
    position: { x: 400, y: 50 },
    data: {
      titleEn: 'Centralized Purchasing',
      titleAr: 'مشتريات مركزية',
      descEn: 'Manage everything in one place',
      descAr: 'إدارة كل شيء في مكان واحد',
      icon: ShoppingCart,
      color: '#10b981',
    },
  },
  {
    id: 'feature-2',
    type: 'feature',
    position: { x: 750, y: 50 },
    data: {
      titleEn: 'Vendor Management',
      titleAr: 'إدارة الموردين',
      descEn: 'Find and manage suppliers easily',
      descAr: 'العثور على الموردين وإدارتهم بسهولة',
      icon: Handshake,
      color: '#3b82f6',
    },
  },
  {
    id: 'feature-3',
    type: 'feature',
    position: { x: 400, y: 500 },
    data: {
      titleEn: 'Automated Approvals',
      titleAr: 'موافقات آلية',
      descEn: 'Faster, error-free approvals',
      descAr: 'موافقات أسرع وبدون أخطاء',
      icon: Clock,
      color: '#f59e0b',
    },
  },
  {
    id: 'feature-4',
    type: 'feature',
    position: { x: 750, y: 500 },
    data: {
      titleEn: 'Secure & Compliant',
      titleAr: 'آمن ومتوافق',
      descEn: 'Built for Saudi businesses',
      descAr: 'مصمم للشركات السعودية',
      icon: Shield,
      color: '#8b5cf6',
    },
  },
];

export const initialEdges: Edge[] = [
  // Main flow
  {
    id: 'e1',
    source: 'step-0',
    target: 'step-1',
    type: 'smoothstep',
    animated: false,
    style: { stroke: '#10b981', strokeWidth: 2 },
    markerEnd: { type: MarkerType.ArrowClosed, color: '#10b981' },
  },
  {
    id: 'e2',
    source: 'step-1',
    target: 'step-2',
    type: 'smoothstep',
    animated: false,
    style: { stroke: '#10b981', strokeWidth: 2 },
    markerEnd: { type: MarkerType.ArrowClosed, color: '#10b981' },
  },
  {
    id: 'e3',
    source: 'step-2',
    target: 'step-3',
    type: 'smoothstep',
    animated: false,
    style: { stroke: '#10b981', strokeWidth: 2 },
    markerEnd: { type: MarkerType.ArrowClosed, color: '#10b981' },
  },
  {
    id: 'e4',
    source: 'step-3',
    target: 'step-4',
    type: 'smoothstep',
    animated: false,
    style: { stroke: '#10b981', strokeWidth: 2 },
    markerEnd: { type: MarkerType.ArrowClosed, color: '#10b981' },
  },
  {
    id: 'e5',
    source: 'step-4',
    target: 'step-5',
    type: 'smoothstep',
    animated: false,
    style: { stroke: '#10b981', strokeWidth: 2 },
    markerEnd: { type: MarkerType.ArrowClosed, color: '#10b981' },
  },
  {
    id: 'e6',
    source: 'step-5',
    target: 'step-6',
    type: 'smoothstep',
    animated: false,
    style: { stroke: '#10b981', strokeWidth: 2 },
    markerEnd: { type: MarkerType.ArrowClosed, color: '#10b981' },
  },
  
  // Feature connections
  {
    id: 'f1',
    source: 'step-2',
    target: 'feature-1',
    type: 'straight',
    style: { stroke: '#6b7280', strokeWidth: 1, strokeDasharray: '5,5' },
  },
  {
    id: 'f2',
    source: 'feature-1',
    target: 'feature-2',
    type: 'straight',
    style: { stroke: '#6b7280', strokeWidth: 1, strokeDasharray: '5,5' },
  },
  {
    id: 'f3',
    source: 'step-4',
    target: 'feature-3',
    type: 'straight',
    style: { stroke: '#6b7280', strokeWidth: 1, strokeDasharray: '5,5' },
  },
  {
    id: 'f4',
    source: 'feature-3',
    target: 'feature-4',
    type: 'straight',
    style: { stroke: '#6b7280', strokeWidth: 1, strokeDasharray: '5,5' },
  },
];